export const FETCH_EVENTS_PER_HOUR = 'FETCH_ALL_EVENTS_PER_HOUR';
export const FETCH_EVENTS_PER_DAY= 'FETCH_ALL_EVENTS_PER_DAY'
export const FETCH_STATS_PER_DAY= 'FETCH_ALL_STATS_PER_DAY'
export const FETCH_STATS_PER_HOUR= 'FETCH_ALL_STATS_PER_HOUR'
export const FETCH_POI= 'FETCH_POI'
export const FETCH_STATS_POI= 'FETCH_STATS_POI'
export const FETCH_EVENTS_POI= 'FETCH_EVENTS_POI'
